Commited by using jll.Git.sh @ 2017-11-13 01:18:02
Changes as follows:
M  BashShellLibrary
M  jll.file.split_or_splice.sh
M  jll.test.sh

diff --git a/BashShellLibrary b/BashShellLibrary
--- a/BashShellLibrary
+++ b/BashShellLibrary
@@ -4,7 +4,8 @@
 # V0 - Original Template is built by jielong.lin @2016-2-1
 # V1 - Add "Lfn_Sys_PathConvertToAbsolutePath" by jielong.lin @2016-2-2
 # V2 - Optimize "eval output with ()" by jielong.lin @2016-11-17
-# V3 - Improve the Rotate Progress Bar by Lfn_Sys_Rotate_With_SIGNAL 
+# V3 - Improve the Rotate Progress Bar by Lfn_Sys_Rotate_With_SIGNAL
+# V4 - Add "Lfn_Progressbar_MonitorByte" by jielong.lin @2017-11-13 
 
 #------------------------------
 # Constant Variable Definition
@@ -1263,6 +1264,75 @@ function Lfn_Stdin_GetDigit()
 
     eval $1="${LvSgdNum}"
 }
+
+
+
+## Lfn_Progressbar_MonitorByte "$(pwd)" &
+## __pbmb_bgpid=$!
+## sleep 20
+## echo
+## kill -12 ${__pbmb_bgpid} >/dev/null 
+##
+function Lfn_Progressbar_MonitorByte()
+{
+    LvPbInterval=0.05
+    LvPbTcount="0"
+
+    if [ $# -ne 1 ]; then
+        Lfn_Sys_FuncComment
+        exit 0
+    fi
+
+    Lfn_Sys_PathConvertToAbsolutePath LvPbPath "$1" 
+    if [ -z "${LvPbPath}" -o ! -e "${LvPbPath}" ]; then
+        echo "Sorry, Exit because of the invalid path\"${LvPbPath}\""
+        exit 0
+    fi
+
+    export __jllutil_rotate_status=1
+
+    # When SIGUSR2(=12) is received, run "export __jllutil_rotate_status=0" 
+    trap "export __jllutil_rotate_status=0"  12
+
+    echo ""
+    Lfn_Cursor_Mov "3" "right"
+    LvPbOffs=2
+    while [ x"${__jllutil_rotate_status}" = x"1" ]; do
+        LvPbData="$(du -sh ${LvPbPath} | awk -F ' ' '{print $1}')"
+        LvPbTcount=`expr ${LvPbTcount} + 1`
+        case  ${LvPbTcount}  in
+        1)
+            echo -ne "- ${LvPbData}"
+            Lfn_Cursor_Mov "$[ ${LvPbOffs}+${#LvPbData} ]" "left"
+            sleep  ${LvPbInterval}
+        ;;
+        2)
+            echo -ne "\\ ${LvPbData}"
+            Lfn_Cursor_Mov "$[ ${LvPbOffs}+${#LvPbData} ]" "left"
+            sleep  ${LvPbInterval}
+        ;;
+        3)
+            echo -ne "| ${LvPbData}"
+            Lfn_Cursor_Mov "$[ ${LvPbOffs}+${#LvPbData} ]" "left"
+            sleep  ${LvPbInterval}
+        ;;
+        4)
+            echo -ne "/ ${LvPbData}"
+            Lfn_Cursor_Mov "$[ ${LvPbOffs}+${#LvPbData} ]" "left"
+            sleep  ${LvPbInterval}
+        ;;
+        *)
+            LvPbTcount="0"
+            sleep  ${LvPbInterval}
+        ;;
+        esac
+        echo -ne "${CvAccOff}\033[K${CvAccOff}"
+    done
+
+    trap 12 # Restore signal SIGUSR2 to default action.
+}
+
+
 
 
 
